site_name: fingers in the pi

theme:
    name: readthedocs

nav:
    - Home: index.md
    - "Initial set-up": 
        - Installing an OS on the Pi: initial_setup/installing_os.md
        - Enabling access via SSH: initial_setup/ssh_setup.md
        - Using VS Code for remote development: initial_setup/vscode_setup.md
    - Projects: 
        - projects.md
